import type { Metadata } from "next";
import { Geist, Geist_Mono, MuseoModerno, Zen_Dots } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/organisms/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const MuseoModernoFont = MuseoModerno({
  variable: "--font-museo",
  subsets: ["latin"],
});

const zenDots = Zen_Dots({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-zen-dots",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${zenDots.variable} ${MuseoModernoFont.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
